name: sampl
channels:
  - conda-forge
  - defaults
dependencies:
  - plotnine
  - lxml
  - matplotlib=3.7.3
  - statsmodels
  - python-louvain
  - pillow
  - openpyxl
  - tqdm
  - pytables
  - simpy
  - seaborn
  - python=3.10.4
  - tifffile
  - scikit-learn
  - scipy
  - netgraph
  - numpy
  - lmfit
  - pandas
  - scikit-image
  - ipykernel
  - notebook
  - jupyter_client<8
  - pyzmq<25